package visualization;


import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import perceptron.Algorithm;
import perceptron.Datastructrue;
import perceptron.DisplayModel2Table;
import perceptron.GeneralizedTableModel;
import perceptron.Loaddata;
import static perceptron.Loaddata.getfearture;
import static perceptron.Loaddata.loadData;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jessyli
 */
public class DisplayFrame extends javax.swing.JFrame {

    static Algorithm algorithm = new Algorithm();
    /**
     * Creates new form DisplayFrame
     */
    public DisplayFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        featureTbl = new javax.swing.JTable();
        proccessBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        featureTbl.setModel(weightTblModel);
        jScrollPane1.setViewportView(featureTbl);

        proccessBtn.setText("Proccess");
        proccessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proccessBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("confusion matix");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        jLabel1.setText("percentage");

        jTextField5.setText("jTextField5");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(proccessBtn)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(proccessBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void proccessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proccessBtnActionPerformed
        // TODO add your handling code here:
        //featureTbl.addColumn(new TableColumn());
        
        double percentage = algorithm.getpercentage();
        double[] weights = algorithm.getWeight();
        List<List<Object>> dataList = weightTblModel.getDataList();
        for(int i=0; i<weights.length; i++) {
            List<Object> item = dataList.get(i);
            item.set(1, weights[i]);
        }
        
       String[][] m = new String[2][2];
        for(int i=0; i<2; i++) {
            for(int j=0; j<2; j++){
           m[i][j] = Double.toString(algorithm.getconfusionmatrix()[i][j]);
            //System.out.println(algorithm.getconfusionmatrix()[i][j]);
}
        }
        String str[] = new String[1];
        DecimalFormat   df  = new DecimalFormat("######0.00");
        str[0] = df.format(percentage);
        
        
        jTextField1.setText(m[0][0]);
        jTextField2.setText(m[0][1]);
        jTextField3.setText(m[1][0]);
        jTextField4.setText(m[1][1]);
        jTextField5.setText(str[0]);
        
        featureTbl.repaint();
    }//GEN-LAST:event_proccessBtnActionPerformed

    public static void set(Algorithm a){
        algorithm = a;
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        List<String[]> featureList = loadData("/Users/jessyli/Documents/perceptrondatatxt.txt");
        List<Datastructrue> doubleFeatureList = getfearture(featureList);
        List<Datastructrue> traindatalist = new ArrayList<Datastructrue>();
        List<Datastructrue> testdatalist = new ArrayList<Datastructrue>();
        int traindatasize = (int) (featureList.size() * 0.9);
        int negativenum = Loaddata.negativenum;
        int positivenum = Loaddata.positivenum;
        for (int i = 0; i < (int)(positivenum*0.9); i++) {
            Datastructrue data = new Datastructrue();
            data.setFeature(doubleFeatureList.get(i).getFeature());
            data.setLabel(doubleFeatureList.get(i).getLabel());
            traindatalist.add(data);
        }
        for (int i = positivenum; i < (positivenum + (int)(negativenum*0.9)); i++) {
            Datastructrue data = new Datastructrue();
            data.setFeature(doubleFeatureList.get(i).getFeature());
            data.setLabel(doubleFeatureList.get(i).getLabel());
            traindatalist.add(data);
        }
        for (int i = (int)(positivenum*0.9); i < positivenum; i++) {
            Datastructrue data = new Datastructrue();
            data.setFeature(doubleFeatureList.get(i).getFeature());
            data.setLabel(doubleFeatureList.get(i).getLabel());
            //System.out.println(data.getLabel());
            testdatalist.add(data);
        }
        for (int i = (positivenum+(int)(negativenum*0.9)); i < positivenum+negativenum; i++) {
            Datastructrue data = new Datastructrue();
            data.setFeature(doubleFeatureList.get(i).getFeature());
            data.setLabel(doubleFeatureList.get(i).getLabel());
            testdatalist.add(data);
        }

        System.out.println("traindatalistsize"+traindatalist.size());
        System.out.println("testdatalistsize"+testdatalist.size());
        System.out.println("featuredatalistsize"+featureList.size());
        Algorithm algorithm = new Algorithm();
        algorithm.setTestdatalist(testdatalist);
        algorithm.setTraindatalist(traindatalist);
        algorithm.train(traindatalist);
        algorithm.test(testdatalist);
        DisplayFrame.set(algorithm);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayFrame().setVisible(true);
            }
        });
    }
    GeneralizedTableModel weightTblModel = new GeneralizedTableModel();
    DisplayModel2Table DisplayModel2Table = new DisplayModel2Table();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable featureTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton proccessBtn;
    // End of variables declaration//GEN-END:variables
}
